

#
# Demo config file for dts2csv.py from MetaindeX Toolbox https://metaindex.fr/webapp/toolbox
#
# In this example, we retrieve Latin Collections from Perseids project DTS API.
#
# Author: Laurent ML - metaindex.fr 2021
# If you find this tools useful somehow, please reference MetaindeX project when possible.
# 
# GNU GENERAL PUBLIC LICENSE
# Version 3, 29 June 2007
# 
# Copyright (C) 2007 Free Software Foundation, Inc. <https://fsf.org/>
# 
# See full version of LICENSE in <https://fsf.org/>
#

from os.path import expanduser
home = expanduser("~")

# path to dependencies. We suppose here we work under Linux style path separator
# only needed if TRANSFORM_TEI_TO_TXT or TRANSFORM_TEI_TO_HTML are set to True
SAXON_JAR_PATH=home+"/dev/tei/install/SaxonHE10-5J/saxon-he-10.5.jar"

## Path to TEI-XSL Stylesheets
## only needed if TRANSFORM_TEI_TO_TXT or TRANSFORM_TEI_TO_HTML are set to True
## shall contain at least following files:
## <TEI_XSL_STYLESHEETS_PATH>/html5/html5.xsl
## <TEI_XSL_STYLESHEETS_PATH>/txt/tei-to-text.xsl
TEI_XSL_STYLESHEETS_PATH=home+"/dev/tei/install/tei-xsl"

# API URLs
rootUrl="https://dts.perseids.org/" # svgd les urls deja utilises
# tres important!!!
COLLECTIONS_URL=rootUrl+"collections"
DOCUMENTS_URL=rootUrl+"documents"
NAVIGATION_URL=rootUrl+"navigation"
# premier formulaire test

#import requests
# envoyer requete python 404?
#st.warning
#st.success

DATASET_ID="perseids" # used to name the dataset in the csv
# split string of rooturl

# where to start from
ROOT_COLLECTION_ID="urn:perseids:latinLit"

#collaborer avec le projet vue.js?

# where to store generated files
TARGET_PATH=home+"/tmp/dts/perseids/"+"latin"

# set to None for no max depth
MAX_DEPTH=None


# set True to download TEI files
RETRIEVE_FILES=True

# Transorm TEI into Text and HTML requires SAXON and TEI-XSL
TRANSFORM_TEI_TO_TXT=True
TRANSFORM_TEI_TO_HTML=False

# if true, put TEI plain text contents into (resources) CSV file
# This option needs TRANSFORM_TEI_TO_TXT=True
INLINE_TXT_IN_CSV=True

# -------------------------------------------

# This function is called every time we try to download a TEI file
# if this function returns False we will skip the file
# it it returns True we will actually download it.
#
# if this function is missing, it is assumed to be always True
def config_filterResource(resourceCsvData,resourceJsonData):
    return True # retrieve all TEI files
    #return resourceCsvData["language"]=="en" # retrieve only TEI files marked as english language

# moins pressant

# CSV ids might have some unicity or syntaxic constraints which can be handled here,
# to be compatible with Lucene query syntax (used by MetaindeX)
def config_idDts2idCsv(dtsId,dtsJsonData):
    return dtsId.replace('urn:','').replace(':','.').replace('urn.','')


# -------------------------------------------

# utility function called from DTS/CSV mapping table
# replace carriage return by "__CR__" string, so that it can stay in a single line in CSV file.
# this string is typically replaced back to carriage return when importing CSV file into metaindex app.
def normalizeText(text):
    return text.replace("\n","__CR__").replace("  "," ").replace(";",".")
    
    # pyhton built in

# -------------------------------------------

# DTS/CSV mapping table
# list of DTS 'path' to put into CSV columns
# at least 'url', 'urn', '@id', 'members' (and 'parent'), and '@type' are generated by default, others shall be listed hereunder
ATTRS_LIST={
    "Collection" :{ "totalItems" : {"csvName":"nbChildren", "mandatory":True}, 
                    "title" : {"csvName":"title", "mandatory":True, "transform":normalizeText},
                    
                },
    
    
    "Resource":{ 
                "title" : {"csvName":"title", "mandatory":True, "transform":normalizeText},
                "description" : {"csvName":"description", "mandatory":True, "transform":normalizeText},
                "dts:dublincore/dc:language" : {"csvName":"language", "mandatory":True},
                
                
            }
 }
